@Library('sharedLib@main') _
def clusterNS

pipeline {
    agent any

    parameters {
        choice(name: 'CronJob', choices: getCronJobNames(env.JOB_NAME), description: 'CronJob Name')
    }

    stages {
        stage('Set NS variable') {
            steps {
                script {
                    // Get the parent of the parent-folder of the job
                    clusterNS = env.JOB_NAME.split('/')[0]
                    env.clusterName = clusterNS.split('-')[0]
                    env.clusterNS = clusterNS.split('-')[1]
                }
                echo "NS variable is set to: ${clusterNS}"
                echo "Cluster variable is set to: ${clusterName}"
            }
        }
        stage('Clone KF Devops Tools') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'rammanokar_github', keyFileVariable: 'SSH_KEY')]) {
                    sh '''#!/usr/bin/env bash
                    export GIT_SSH_COMMAND="ssh -i $SSH_KEY"
                    rm -rf kf-devops-tools
                    git clone git@github.com:OrangeScape/kf-devops-tools.git
                    '''
                }
            }
        }
        stage('Suspend CronJobs') {
            steps {
                sh'''
                cd kf-devops-tools/activateClusters/
                source activate-\${clusterName} 1 # CronJobs are present only in Cluster 1
                kubens \${clusterNS}
                kubectl patch cronjobs \${CronJob}-cron -p '{"spec" : {"suspend" : true }}'
                '''
            }
        }
    }
}
