def clusterNS

pipeline {
    agent any

    environment {
        SSH_KEY = credentials('rammanokar_github')
    }

    parameters {
        choice(name: 'clusterID', choices: ['1', '2', '3'], description: 'Cluster ID list; ignore for single cluster')
    }

    stages {
        stage('Set NS variable') {
            steps {
                script {
                    // Get the parent of the parent-folder of the job
                    clusterNS = env.JOB_NAME.split('/')[0]
                    env.clusterNS = clusterNS
                }
                echo "NS variable is set to: ${clusterNS}"
            }
        }
        stage('Check & Approve') {
            steps {
                input message: "Do you want to scled down the deployments in $clusterNS namespace? Please confirm.", ok: 'Proceed', submitterParameter: 'APPROVER'
            }
        }
        stage('Clone KF configs') {
            steps {
                    sh '''#!/usr/bin/env bash
                    export GIT_SSH_COMMAND="ssh -i $SSH_KEY"
                    rm -rf kf-configs
                    git clone --depth 1 git@github.com:OrangeScape/kf-configs.git
                    '''
            }
        }        
        stage('Scale down Deployments') {
            steps {
                sh"""#!/usr/bin/env bash
                cd kf-configs
                ./create-pegasi.sh $clusterNS 2>&1 >/dev/null || true
                source activate $clusterNS ${params.clusterID}
                if [[ $JOB_NAME == *"KF4"* ]]; then
                    KF_VERSION="4"
                else
                    KF_VERSION="3"
                fi
                deploymentList="\$(kubectl get deployment -l "app.kissflow.com/version in (\$KF_VERSION)" -o jsonpath="{.items[*].metadata.name}")"
                kubectl scale deployment --replicas=0 \$deploymentList
                echo "sleeping for 45 seconds..."
                sleep 45
                """
            }
        }
    }
}
